blog/urls.py
from django.urls import path

from .views import (ArticlePreview, about, article_list, author_article_list,
                    contact, post)

app_name = 'blog'
urlpatterns = [
    path('', article_list, name='article_list'),
    path('<slug:username>/', author_article_list, name='author_article_list'),
    path('about/', about, name='about'),
    path('post/<slug:slug>/', post, name='post'),
    path('contact/', contact, name='contact'),
    path('preview/<int:pk>', ArticlePreview.as_view(), name='article_preview'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
from account.models import User
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس')
    status = models.BooleanField(
        default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی‌ها'
        ordering = ['position']

    def __str__(self):
        return self.title


class Article(models.Model):
    PENDDING = 'P'
    DRAFT = 'D'
    INSTIGATION = 'I'
    BACK = 'B'
    STATUS_CHOICES = [
        (PENDDING, 'منتشرشده'),
        (DRAFT, 'پیش‌نویس'),
        (INSTIGATION, 'در حال برسی'),
        (BACK, 'برگشت داده شده'),
    ]
    title = models.CharField(max_length=255, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس')
    category = models.ManyToManyField(Category, verbose_name='دسته‌بندی')
    description = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to='images', verbose_name='تصویر')
    publish = models.DateTimeField(
        default=timezone.now, verbose_name='زمان انتشار')
    create = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')
    update = models.DateTimeField(
        auto_now=True, verbose_name='تاریخ بروزرسانی')
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')

    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,
                               verbose_name='نویسنده', related_name='articles')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقاله‌ها'

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    def jcreate(self):
        return jalali_converter(self.create)
    jcreate.short_description = 'تاریخ ساخت'

    def jupdate(self):
        return jalali_converter(self.update)
    jupdate.short_description = 'تاریخ بروزرسانی'

    def get_category(self):
        return '، '.join([category.title for category in self.category.all()])
    get_category.short_description = 'دسته‌بندی'

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug': self.slug})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.models import User
from django.views.generic import DetailView
from account.mixins import AuthorAccessMixin
# Create your views here.


def article_list(request):
    queryset = Article.objects.filter(status='P')
    categories = Category.objects.all()
    context = {'queryset': queryset, 'categories': categories}
    return render(request, 'index.html', context)


def about(request):
    context = {}
    return render(request, 'about.html', context)


def post(request, slug):
    obj = get_object_or_404(Article, slug=slug, status='P')
    context = {'object': obj}
    return render(request, 'post.html', context)


def contact(request):
    context = {}
    return render(request, 'contact.html', context)


def author_article_list(request, username):
    # author = User.objects.get(username=username)
    author = get_object_or_404(User, username=username)
    articles = author.articles.filter(status='P')
    context = {'author': author,
               'articles': articles}
    return render(request, 'author-article-list.html', context)


class ArticlePreview(AuthorAccessMixin, DetailView):
    template_name = 'post.html'
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)

blog/templates/about.html
{% extends 'base.html' %} {% load static %} {% block title %}درباره ما{%endblock %} {% block main %}
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe
          nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis
          sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
          consectetur?
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius
          praesentium recusandae illo eaque architecto error, repellendus iusto
          reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in
          officia voluptas voluptatibus, minus!
        </p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut
          consequuntur magnam, excepturi aliquid ex itaque esse est vero natus
          quae optio aperiam soluta voluptatibus corporis atque iste neque sit
          tempora!
        </p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

blog/templates/article_confirm_delete.html
{% extends 'registration/base.html' %}
{% block main %}
<div class="col-md-8 text-center mx-auto">
    
    <div class="card card-danger ">
        <div class="card-header">
          <h3 class="card-title mb-0 float-left">حذف مقاله</h3>
        </div>
            <div class="card-body py-4">
                <form method="post">{% csrf_token %}
                    <p class="py-2 text-bold text-dark">آیا مطمئن هستید مقاله «{{article.title}}» از «{{user.get_full_name}}» را حذف کنید؟</p>
                    {{ form }}
                    <input type="submit" value="بله" class="btn btn-danger">
                </form> 
            </div>
        </div>
</div>
{% endblock %}

blog/templates/author-article-list.html
{% extends 'base.html' %} {% load static %} {% block title %}صفحه اصلی{%endblock%}
{% block pageheading %} {{author}} {% endblock %}
{% block subheading %} {{author.get_full_name}} {% endblock %}
{% block image %}{%static '/blog/assets/img/home-bg.jpg' %}{% endblock%}
{% block main %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      {% for article in articles%}
        <!-- Post preview-->
        <div class="post-preview">
          <a href="{% url 'blog:post' article.slug %}">
            <h2 class="post-title">
              {{ article.title }}
            </h2>
            <h3 class="post-subtitle">
              {{ article.description | truncatewords:30| striptags | cut:'&nbsp;' }}
            </h3>
          </a>
          <div>
            {% for cat in article.category.all %}
              <a href="#">#{{cat.title}} </a>
            {% endfor %}
          </div>

          <p class="post-meta">
            نوشته شده توسط
            <a href="#!">{{article.author.get_full_name}}</a>
              در {{article.jpublish}}
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />

      {% endfor %}
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary text-uppercase" href="#!">Older Posts &larr; </a>
      </div>
    </div>
  </div>
</div>
{% endblock main %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>وبلاگ | {% block title %}{% endblock%}</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href='{% static "blog/css/styles.css" %}' rel="stylesheet" />
    <link href='{% static "blog/css/rtl.css" %}' rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blog:article_list'%}"
          >سینا رسولی</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs{%
          block
          body
          %}{%
          endblock
          %}-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a
                class="nav-link px-lg-3 py-3 py-lg-4"
                href="{% url 'blog:article_list'%}"
                >خانه</a
              >
            </li>
            {% for cat in categories%}
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="#"
                >{{cat.title}}</a
              >
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- Page Header-->
    <header
      class="masthead"
      style="background-image: url('{% block image %}{% endblock %}')"
    >
      <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="page-heading">
              <h1>{% block pageheading %}{% endblock %}</h1>
              <span class="subheading"
                >{% block subheading%}{% endblock %}</span
              >
            </div>
          </div>
        </div>
      </div>
    </header>
    {% block main %}{% endblock %}
    <!-- Footer-->
    <footer class="border-top">
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#!">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <div class="small text-center text-muted fst-italic">
              Copyright &copy; Your Website 2022
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
  </body>
</html>

blog/templates/contact.html
{% extends 'base.html' %} {% load static %} {% block title %}درباره ما{%endblock%}
{% block main %}

<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <!-- * * * * * * * * * * * * * * *-->
          <!-- * * SB Forms Contact Form * *-->
          <!-- * * * * * * * * * * * * * * *-->
          <!-- This form is pre-integrated with SB Forms.-->
          <!-- To make this form functional, sign up at-->
          <!-- https://startbootstrap.com/solution/contact-forms-->
          <!-- to get an API token!-->
          <form id="contactForm" data-sb-form-api-token="API_TOKEN">
            <div class="form-floating">
              <input
                class="form-control"
                id="name"
                type="text"
                placeholder="Enter your name..."
                data-sb-validations="required"
              />
              <label for="name">Name</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="email"
                type="email"
                placeholder="Enter your email..."
                data-sb-validations="required,email"
              />
              <label for="email">Email address</label>
              <div class="invalid-feedback" data-sb-feedback="email:required">
                An email is required.
              </div>
              <div class="invalid-feedback" data-sb-feedback="email:email">
                Email is not valid.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="phone"
                type="tel"
                placeholder="Enter your phone number..."
                data-sb-validations="required"
              />
              <label for="phone">Phone Number</label>
              <div class="invalid-feedback" data-sb-feedback="phone:required">
                A phone number is required.
              </div>
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="message"
                placeholder="Enter your message here..."
                style="height: 12rem"
                data-sb-validations="required"
              ></textarea>
              <label for="message">Message</label>
              <div class="invalid-feedback" data-sb-feedback="message:required">
                A message is required.
              </div>
            </div>
            <br />
            <!-- Submit success message-->
            <!---->
            <!-- This is what your users will see when the form-->
            <!-- has successfully submitted-->
            <div class="d-none" id="submitSuccessMessage">
              <div class="text-center mb-3">
                <div class="fw-bolder">Form submission successful!</div>
                To activate this form, sign up at
                <br />
                <a href="https://startbootstrap.com/solution/contact-forms"
                  >https://startbootstrap.com/solution/contact-forms</a
                >
              </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage">
              <div class="text-center text-danger mb-3">
                Error sending message!
              </div>
            </div>
            <!-- Submit Button-->
            <button
              class="btn btn-primary text-uppercase disabled"
              id="submitButton"
              type="submit"
            >
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %} {% load static %} {% block title %}صفحه اصلی{%endblock%}
{% block pageheading %} صفحه اصلی {% endblock %}
{% block subheading %} این صفحه اصلی است {% endblock %}
{% block image %}{%static '/blog/assets/img/home-bg.jpg' %}{% endblock%}
{% block main %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      {% for blog in queryset%}
        <!-- Post preview-->
        <div class="post-preview">
          <a href="{% url 'blog:post' blog.slug %}">
            <h2 class="post-title">
              {{ blog.title }}
              
              {% if article.is_special %}
              <span class="badge badge-danger text-danger">ویژه</span>
              {% endif %}
              
            </h2>
            <h3 class="post-subtitle">
              {{ blog.description | truncatewords:30 | striptags | cut:'&nbsp;' }}
            </h3>
          </a>
          <div>
            {% for cat in blog.category.all %}
              <a href="#">#{{cat.title}} </a>
            {% endfor %}
          </div>

          <p class="post-meta">
            نوشته شده توسط
            <a href="{% url 'blog:author_article_list' blog.author %}">{{blog.author.get_full_name}}</a>
              در {{blog.jpublish}}
          </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />

      {% endfor %}
      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary text-uppercase" href="#!">Older Posts &larr; </a>
      </div>
    </div>
  </div>
</div>
{% endblock main %}

blog/templates/post.html
{% extends 'base.html' %} {% load static %} {% block title %}پست{% endblock %}
{% block pageheading %} {{ object.title }} {% if article.is_special %} <span class="badge badge-danger">ویژه</span> {% endif%} {% endblock %} {% block subheading %}
{{ object.description | truncatewords:20 }} {% endblock %} 
{% block image %}{{object.thumbnail.url}} {% endblock%}
{% block main %}
<!-- Post Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!-- <h2 class="section-heading">The Final Frontier</h2> -->
        <!-- <blockquote class="blockquote">
        </blockquote> -->
        {% if object.is_special %}
          {% if user.is_special or user == object.author or user.is_superuser %}  
          {{object.description|linebreaks|safe}}
          {% else %}
            <h4>این یک مقاله ویژه هست برای مشاهده باید <a href="#">اشتراک ویژه</a> تهیه کنید.</h4>
          {% endif %}
        {% else %}        
          {{object.description|linebreaks|safe}}
        {% endif %}
      </div>
    </div>
  </div>
</article>
{% endblock %}