account/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView
from .views import (ArticleDelete, CreateArticle, Home, LoginView,
                    PasswordChangeDoneView, PasswordChangeView,
                    PasswordResetCompleteView, PasswordResetConfirmView,
                    PasswordResetDoneView, PasswordResetView, Profile,
                    UpdateArticle)

app_name = 'account'
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        PasswordChangeView.as_view(),
        name="password_change"
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("password_reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += [
    path('home/', Home.as_view(), name='home'),
    path('create/', CreateArticle.as_view(), name='create-article'),
    path('update/<int:pk>/', UpdateArticle.as_view(), name='update-article'),
    path('delete/<int:pk>/', ArticleDelete.as_view(), name='delete-article'),
    path('profile/', Profile.as_view(), name='profile'),
]

accounts/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path
from .views import home
app_name = 'accounts'
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    # path("logout/", views.LogoutView.as_view(), name="logout"),
    # path(
    #     "password_change/", views.PasswordChangeView.as_view(), name="password_change"
    # ),
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

urlpatterns += [
    path('home/', home, name='home'),
]

blog/urls.py
from django.urls import path

from .views import (ArticlePreview, about, article_list, author_article_list,
                    contact, post)

app_name = 'blog'
urlpatterns = [
    path('', article_list, name='article_list'),
    path('<slug:username>/', author_article_list, name='author_article_list'),
    path('about/', about, name='about'),
    path('post/<slug:slug>/', post, name='post'),
    path('contact/', contact, name='contact'),
    path('preview/<int:pk>', ArticlePreview.as_view(), name='article_preview'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    is_author = models.BooleanField(
        default=False, verbose_name='وضعیت نویسندگی')
    
    email = models.EmailField(unique=True, verbose_name='آدرس ایمیل')

blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
from account.models import User
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس')
    status = models.BooleanField(
        default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی‌ها'
        ordering = ['position']

    def __str__(self):
        return self.title


class Article(models.Model):
    PENDDING = 'P'
    DRAFT = 'D'
    INSTIGATION = 'I'
    BACK = 'B'
    STATUS_CHOICES = [
        (PENDDING, 'منتشرشده'),
        (DRAFT, 'پیش‌نویس'),
        (INSTIGATION, 'در حال برسی'),
        (BACK, 'برگشت داده شده'),
    ]
    title = models.CharField(max_length=255, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس')
    category = models.ManyToManyField(Category, verbose_name='دسته‌بندی')
    description = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to='images', verbose_name='تصویر')
    publish = models.DateTimeField(
        default=timezone.now, verbose_name='زمان انتشار')
    create = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')
    update = models.DateTimeField(
        auto_now=True, verbose_name='تاریخ بروزرسانی')
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')

    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,
                               verbose_name='نویسنده', related_name='articles')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقاله‌ها'

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = 'تاریخ انتشار'

    def jcreate(self):
        return jalali_converter(self.create)
    jcreate.short_description = 'تاریخ ساخت'

    def jupdate(self):
        return jalali_converter(self.update)
    jupdate.short_description = 'تاریخ بروزرسانی'

    def get_category(self):
        return '، '.join([category.title for category in self.category.all()])
    get_category.short_description = 'دسته‌بندی'

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug': self.slug})

account/forms.py
from django import forms

from .models import User


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):

        user = kwargs.pop('user')
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        if not user.is_superuser:
            self.fields['username'].disabled = True
            self.fields['email'].disabled = True
            self.fields['is_author'].disabled = True

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_author']

account/views.py
from django.contrib.auth import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from blog.models import Article

from .forms import ProfileForm
from .mixins import (AuthorAccessMixin, AuthorsAccessMixin, FormFieldsMixin,
                     FormValidMixin, SuperUserAccessMixin)
from .models import User

# Create your views here.


class Home(LoginRequiredMixin, AuthorsAccessMixin, ListView):
    template_name = 'home.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Article.objects.all()
        else:
            return Article.objects.filter(author=self.request.user)


class CreateArticle(LoginRequiredMixin, AuthorsAccessMixin, FormFieldsMixin, FormValidMixin, CreateView):
    model = Article
    template_name = 'create_article.html'


class UpdateArticle(AuthorAccessMixin, FormFieldsMixin, FormValidMixin, UpdateView):
    model = Article
    template_name = 'create_article.html'


class ArticleDelete(SuperUserAccessMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('account:home')
    template_name = 'article_confirm_delete.html'


class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'registration/profile.html'

    success_url = reverse_lazy('account:profile')

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class LoginView(views.LoginView):

    def get_success_url(self):
        user = self.request.user
        if user.is_superuser or user.is_author:
            return reverse_lazy('account:home')

        else:
            return reverse_lazy('account:profile')


class PasswordChangeView(views.PasswordChangeView):
    success_url = reverse_lazy('account:password_change_done')
    template_name='registration/account_password_change_form.html'

class PasswordResetView(views.PasswordResetView):

    email_template_name = "registration/password_reset_email1.html"
    success_url = reverse_lazy("account:password_reset_done")
    template_name = "registration/password_reset_form1.html"


class PasswordResetDoneView(views.PasswordResetDoneView):
    template_name = "registration/password_reset_done1.html"


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    template_name="registration/password_reset_confirm1.html"
    success_url= reverse_lazy('account:password_reset_complete')


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    template_name='registration/account_password_change_done.html'


class PasswordResetCompleteView(views.PasswordResetCompleteView):
    template_name = "registration/password_reset_complete1.html"

    

account/templates/create_article.html
{% extends 'registration/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title mb-0 float-left">افزودن مقاله</h3>
    </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        {{form.title|as_crispy_field}}
                    </div>
                    <div class="col-6">
                        {{form.slug|as_crispy_field}}
                    </div>
                    <div class="col-12">
                        {{form.description|as_crispy_field}}
                    </div>
                    <div class="col-6">
                        {{form.category|as_crispy_field}}
                    </div>
                    <div class="col-6">
                        {{form.thumbnail|as_crispy_field}}
                        {{form.publish|as_crispy_field}}
                    </div>
                    {% if user.is_superuser %}
                        <div class="col-6">
                            {{form.status|as_crispy_field}}
                        </div>
                        <div class="col-6">
                            {{form.author|as_crispy_field}}
                        </div>
                    {% elif user.is_author %}
                        <div class="col-6">
                            <div id="div_id_status" class="mb-3">
                            <label for="id_status" class="form-label requiredField">
                            وضعیت<span class="asteriskField">*</span>
                            </label>
                            <select name="status" class="select form-select" required="" id="id_status">
                                <option value="">---------</option>
                                <option value="D">پیش‌نویس</option>
                                <option value="I">ارسال برای ادمین</option>
                            </select>
                            </div>
                        </div>                     
                    {% endif %}
                    <div class="col-6 mx-3">
                        {{form.is_special|as_crispy_field}}
                    </div>
                </div>
                <button value="submit"class="btn btn-primary">ارسال</button>
                {% if user.is_superuser and request.resolver_match.url_name == 'update-article' %}
                <a class="btn btn-danger text-light"
                    href="{% url 'account:delete-article' request.resolver_match.kwargs.pk %}">
                    حذف 
                </a>
                {% endif %}
            </form>
        </div>
    </div>
       
   
{% endblock %}

account/templates/home.html
{% extends 'registration/base.html' %}
{% load static %}
<h1>home</h1>
{{request.user}}

{% block main %}
  <div class="row">
    <div class="col-12">
    {% if object_list %}
      <div class="card">
        <!-- <div class="card-header">
          <h3 class="card-title">Responsive Hover Table</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>عنوان</th>
                <th>تصویر</th>
                <th>دسته‌بندی</th>
                <th>نویسنده</th>
                <th>محتوا</th>
                <th>زمان انتشار</th>
                <th>مقاله ویژه</th>
                <th>وضعیت</th>
              </tr>
            </thead>
            <tbody>
              {% for article in object_list %}
                <tr>
                  <td>
                    {% if article.status in 'DB'|make_list or user.is_superuser %} 
                    <a href="{% url 'account:update-article' article.id %}">
                      {{article.title}}
                    {% else %}
                      {{article.title}}
                    {%endif%}
                    </a>
                  </td>
                  <td> <img src="{{article.thumbnail.url}}" width="120"></td>
                  <td> {{article.get_category}}</td>
                  <td> {{article.author.get_full_name}}</td>
                  <td> {{article.description|truncatewords:30|striptags}}</td>
                  <td> {{article.jpublish}}</td>
                  <td>
                      {% if article.is_special %}
                        <i class="fa fa-check" style="color: #28a745;"></i>
                        
                      {% else %}
                        <i class="fa fa-minus" style="color: #dc3545;"></i>
                      {% endif %}
                  </td>
                  <td> 
                    {% if article.status == 'P' %}
                      <span class="badge badge-success">منتشرشده</span>
                      <a class="badge badge-primary" href="{% url 'blog:post' article.slug %}" target="_blank">نمایش در سایت</a>
                    {% elif article.status == 'I' %}
                      <span class="badge badge-info">درحال برسی</span>
                      {% if user.is_superuser%}
                        <a href="{%url 'blog:article_preview' article.pk %}" class="badge badge-dark">پیش‌نمایش</a>
                      {% endif %}
                    {% elif article.status == 'B' %}
                      <span class="badge badge-warning">برگشت داده شده</span>
                      <a href="{%url 'blog:article_preview' article.pk %}" class="badge badge-dark">پیش‌نمایش</a>     
                    {% else %}
                    <span class="badge badge-secondary">پیش‌نویس</span>
                    <a href="{%url 'blog:article_preview' article.pk %}" class="badge badge-dark">پیش‌نمایش</a>
                    {% endif%}
                    {% if user.is_superuser %}
                    <span class="badge badge-danger">
                      <a class="text-white" href="{% url 'account:delete-article' article.id %}">
                        حذف مقاله
                      </a>
                    </span>
                    {% endif %}

                  </td>
                  
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
    
    {% else %}
      <h3>مقاله ای برای نمایش وجود ندارد</h3>
    {% endif %}
    </div>
  </div>
{% endblock %}

account/templates/non_field_errors.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/rtl.css' %}"/>
</head>

<body>
    {% if form.non_field_errors %}
        <div class="error">
            {% for err in form.non_field_errors %}
                <p class="error"> {{ err }}</p>
            {% endfor %}
        </div>
    {% endif %}
</body>